name: hmm

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */6 * * *"

env: 
  API_ID: ${{ secrets.API_ID }}
  API_HASH: ${{ secrets.API_HASH }}
  SESSION_NAME: ${{ secrets.SESSION_NAME }}
  PLUGIN: ${{ secrets.PLUGIN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup Env
         run: |
              sudo bash x.sh

       - name: Run Bot
         run: |
              python main.py
